QA-248 add --sc-only option
arenadata/pytest_allure_spec_coverage pull request #23
Opened 2021-08-27 10:49 UTC by skhomuti

Spec collector now can be running as a linter to check that specs coverage is enough
```
============ 3 tests collected, 50% specification coverage in 0.11s ============
! _pytest.outcomes.Exit: Spec coverage percent is 50, but is less than target 100 !
```
```
============ 3 tests collected, 50% specification coverage in 0.01s ============
Spec coverage greater than target 25. 🎉🎉🎉
```

2021-08-30 09:18 UTC, skhomuti commented on src/pytest_allure_spec_coverage/plugin.py
> +    )
`--spec-coverage-target` not required. Do you suggest using it only?

2021-08-31 08:22 UTC, dgusakov requested changes

2021-08-31 08:22 UTC, dgusakov commented on src/pytest_allure_spec_coverage/matcher.py
> +                returncode=ExitCode.NO_TESTS_COLLECTED,
```suggestion
                f"Spec coverage percent is {self.spec_coverage_percent} %, "
                f"and it is less than target {self.config.fail_under} %",
                returncode=ExitCode.NO_TESTS_COLLECTED,
```

2021-08-31 08:22 UTC, dgusakov commented on src/pytest_allure_spec_coverage/matcher.py
> +            terminal.write_line(f"Spec coverage is greater than target {self.config.fail_under}! 🎉🎉🎉")
```suggestion
            terminal.write_line(f"Spec coverage is greater than target {self.config.fail_under} %! 🎉🎉🎉")
```

2021-08-31 10:18 UTC, vgorkavenko approved these changes

2021-08-31 10:33 UTC, dgusakov approved these changes

2021-08-31 10:33 UTC, merged